services:
  - type: web
    name: efootball-api
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && node prisma/seed.js && node index.js
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://efootball-tournament-tpha.vercel.app
      - key: DATABASE_URL
        value: file:./dev.db